-- PROBLEM 2:
--
-- Each new term in the Fibonacci sequence is generated by adding the previous
-- two terms.
--
-- By considering the terms in the Fibonacci sequence whose values do not
-- exceed four million, find the sum of the even-valued terms.

fibs :: [Int]
fibs = 0 : 1 : zipWith (+) fibs (tail fibs)

main = do
    print $ sum ( filter even ( takeWhile (<4000000) fibs ) )
